# Generated by Django 5.1.1 on 2024-10-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kittens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=30)),
                ("age", models.IntegerField(default=0)),
                ("description", models.TextField(max_length=100)),
                ("breed", models.CharField(max_length=50)),
            ],
        ),
    ]
